#!/bin/bash
# gptme autonomous agent startup script.
# Generated by: gptme service init --name dot
set -euo pipefail

AGENT_NAME="dot"
WORK_DIR=/home/skogix/dot
JOURNAL_DIR="$WORK_DIR/journal/$(date +%Y-%m-%d)"
PROMPT_FILE="$WORK_DIR/prompt.md"

mkdir -p "$JOURNAL_DIR" || { echo "gptme agent $AGENT_NAME: cannot create journal dir $JOURNAL_DIR" >&2; exit 1; }
SESSION_ID=$(date +%Y%m%d-%H%M%S)-$$-$RANDOM
SESSION_LOG="$JOURNAL_DIR/session-$SESSION_ID.md"

{
  echo "# Session $SESSION_ID"
  echo
  echo "Agent: $AGENT_NAME"
  echo "Started: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
} > "$SESSION_LOG"

if ! command -v gptme >/dev/null 2>&1; then
  echo "gptme agent $AGENT_NAME: 'gptme' not found on PATH" >&2
  echo "gptme not found on PATH; install gptme or set PATH in the service unit."     >> "$SESSION_LOG"
  exit 127
fi

if [ ! -f "$PROMPT_FILE" ]; then
  echo "gptme agent $AGENT_NAME: missing prompt file $PROMPT_FILE" >&2
  echo "Missing prompt file $PROMPT_FILE." >> "$SESSION_LOG"
  exit 66
fi
if [ ! -r "$PROMPT_FILE" ]; then
  echo "gptme agent $AGENT_NAME: prompt file $PROMPT_FILE is not readable" >&2
  echo "Prompt file not readable: $PROMPT_FILE (check permissions)." >> "$SESSION_LOG"
  exit 66
fi
if [ ! -s "$PROMPT_FILE" ]; then
  echo "gptme agent $AGENT_NAME: prompt file $PROMPT_FILE is empty" >&2
  echo "Prompt file is empty: $PROMPT_FILE (add your agent instructions)." >> "$SESSION_LOG"
  exit 66
fi
# Reject prompts whose first content line is a gptme in-chat command.
# _group_prompt_args strips the leading-newline guard before the chat loop
# dispatch: /shell, /python, /log, etc. as the first line would be dispatched
# as a command rather than sent to the model. /path/to/file-style strings are
# safe because their first word contains more than one slash.
_prompt_fw=$(grep -m1 '[^[:space:]]' "$PROMPT_FILE" | python3 -c "import sys; w=sys.stdin.read().split(); print(w[0] if w else '')")
if [ "${_prompt_fw#/}" != "$_prompt_fw" ]    && [ "$(printf '%s' "$_prompt_fw" | awk -F'/' '{print NF-1}')" -eq 1 ]; then
  echo "gptme agent $AGENT_NAME: prompt.md starts with '$_prompt_fw', a gptme in-chat command; it would be dispatched rather than sent to the model." >&2
  echo "Begin prompt.md with a description or heading (e.g. '# Task')." >&2
  echo "Prompt starts with in-chat command '$_prompt_fw'." >> "$SESSION_LOG"
  exit 66
fi
unset _prompt_fw

# Run one non-interactive gptme session. --non-interactive is passed as a flag
# because gptme reads the flag, not GPTME_NON_INTERACTIVE.
gptme_args=(--non-interactive --no-confirm --workspace "$WORK_DIR")
gptme_args+=(--name "$AGENT_NAME-$SESSION_ID")
if [ -n "${GPTME_AGENT_MODEL:-}" ]; then
  gptme_args+=(--model "$GPTME_AGENT_MODEL")
fi

echo "## Output" >> "$SESSION_LOG"
echo >> "$SESSION_LOG"

cd "$WORK_DIR"
# Prefix a newline so the raw CLI argument never matches a gptme-util subcommand
# or plugin name (checked before _group_prompt_args runs). _group_prompt_args
# strips leading whitespace, so the LLM receives the file content as-is.
# Single-slash commands (e.g. /shell) are rejected above before we reach here.
prompt_arg=$'\n'"$(cat "$PROMPT_FILE")"
exit_code=0
gptme "${gptme_args[@]}" "$prompt_arg" >> "$SESSION_LOG" 2>&1 || exit_code=$?

{
  echo
  echo "Finished: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "Exit code: $exit_code"
} >> "$SESSION_LOG"

echo "gptme agent dot: session $SESSION_ID exited $exit_code (log: $SESSION_LOG)"
exit "$exit_code"
